# project: na

version: '3'

services:
  traefik:
    image: traefik:v2.8@sha256:72164cb63797a902ba7c33dcb75349644bbf762323a0fed961ae25f54635ac93
    restart: unless-stopped
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
    - "80:80"
    - "8080:8080"
    networks: 
      - tk_web

  tk-hosts:
    image: ghcr.io/zekker6/traefik-hosts-generator:v0.5.5@sha256:de14d027b6b6509cca1df2ed5f75615b00d1c57f24609dd851f0d7fe69fa021e
    restart: unless-stopped
    volumes:
      - /etc/hosts:/hosts
    command: "-platform=linux -traefik=true -traefikVersion=2 -traefikUrl=http://traefik:8080/api -file=/hosts -watch=true -freq=10"
    networks:
      - tk_web
    depends_on:
    - traefik


networks:
  tk_web:
    external: true

